### ISSUE TITLE
pymol 2.3 and psico

### ISSUE THREAD

**Issue by alexxy** [speleo3/pymol-psico#4]
I'm using pymol 2.3 and psico. But problem is that i menus like A or D generates error

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/pymol/menu.py", line 1231, in mol_action
    [ 1, 'generate'  ,   mol_generate(self_cmd, sele)       ],
  File "/usr/lib64/python2.7/site-packages/psico/guitweak.py", line 16, in <lambda>
    wrapped = lambda c, s: orig(c, s) + f(c, s)
  File "/usr/lib64/python2.7/site-packages/psico/guitweak.py", line 46, in mol_generate
    from . import pymol_version
ImportError: cannot import name pymol_version

```

**Comment by speleo3** [comment]
I assume you tried this:
```python
run psico/guitweak.py
```
That's not possible (without modifying the script first).

This is correct:
```python
import psico.guitweak
```

This also works:
```python
run psico/fullinit.py
```
